apiVersion: v1
kind: ConfigMap
metadata:
  name: upgrade-defaults-v1
  namespace: sno-ran-du-v4-Y-Z
data:
  # The upgrade step timeout needs to be 30 minutes longer than the auto rollback timeout
  # so that the abort/cleanup can be executed as part of ibgu
  ibgu: |
    ibuSpec:
      seedImageRef:
        image: "quay.io/seed-repo/seed-image:4.Y.Z"
        version: "4.Y.Z"
      oadpContent:
        - name: sno-ran-du-ibu-platform-backup-v4-Y-Z-1
          namespace: openshift-adp
      autoRollbackOnFailure:
        initMonitorTimeoutSeconds: 1800
    plan:
      - actions: ["Prep"]
        rolloutStrategy:
          maxConcurrency: 1
          timeout: 15
      - actions: ["AbortOnFailure"]
        rolloutStrategy:
          maxConcurrency: 1
          timeout: 5
      - actions: ["Upgrade"]
        rolloutStrategy:
          maxConcurrency: 1
          timeout: 60
      - actions: ["AbortOnFailure"]
        rolloutStrategy:
          maxConcurrency: 1
          timeout: 5
      - actions: ["FinalizeUpgrade"]
        rolloutStrategy:
          maxConcurrency: 1
          timeout: 5
